runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/html5-canvas-drawing-app.html
  upload: www/html5-canvas-drawing-app.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)